### ISSUE TITLE
incompatible with catalina

### ISSUE THREAD

**Issue by netseeder** [AyushAgrawalProgrammer/RTL8188FTV_Wifi_AllPlatforms_Driver#1]
Hi Ayush,
i have bought aptech AP103 which one based on Rtl8188FTV chip. wle i was going to install i says it's not incompatible with catalina verson. so could you update it. 
thanks

**Comment by AyushAgrawalProgrammer** [comment]
What was the processor of installation done by you ?
GUI installation may give some error, try using terminal
` git clone https://github.com/AyushAgrawalProgrammer/RTL8188FTV_Wifi_AllPlatforms_Driver.git `
`cd RTL8188FTV_Wifi_AllPlatforms_Driver`
`cd MacOS`
Then you can try typing your installation command for `Installer.pkg`

**Comment by netseeder** [comment]
getting this error..
[https://we.tl/t-Zdlugkf1Ca](url)
